# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{konfig}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Starr Horne"]
  s.date = %q{2010-05-28}
  s.description = %q{ Automatically loads yaml config files and makes them available to your rails app.}
  s.email = %q{starr@chromahq.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "konfig.gemspec",
     "lib/konfig.rb",
     "lib/konfig/adapter.rb",
     "lib/konfig/evaluator.rb",
     "lib/konfig/helpers.rb",
     "lib/konfig/rails/adapters/asset_expansion_adapter.rb",
     "lib/konfig/rails/adapters/smtp_adapter.rb",
     "lib/konfig/rails/railtie.rb",
     "lib/konfig/store.rb",
     "test/fixtures/dynamic.yml",
     "test/fixtures/static.yml",
     "test/helper.rb",
     "test/test_adapter.rb",
     "test/test_evaluator.rb",
     "test/test_konfig.rb",
     "test/test_store.rb"
  ]
  s.homepage = %q{http://github.com/starrhorne/konfig}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Yaml config file manager for rails 3 apps}
  s.test_files = [
    "test/helper.rb",
     "test/test_adapter.rb",
     "test/test_evaluator.rb",
     "test/test_konfig.rb",
     "test/test_store.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

